#!/usr/bin/env bash
# could use this to get the IP address
# ifconfig eth0 | grep inet | grep -v inet6 | awk '{print $2}'
# need to specify the network interface to use, e.g: eth0

SRVC_NAME="32 bit ARMFH User space for TheSkyX"

if [ $# -eq 0 ] || [ $# -lt 1 ]
  then
    printf "\n[-] Install/remove ${SRVC_NAME} \n\n"
		echo ": "
		echo ": Requires at least one command"
    echo ": e.g."
    echo ": install-32bit-userspace install"
    echo ": or..."
    echo ": install-32bit-userspace remove"
    echo ""
		exit 1
fi

ACTION=${1}

install.armhf() {
  printf "\n[-] Add ARMHF\n\n"
  sudo dpkg --add-architecture armhf
  sudo apt update

  printf "\n[-] Install libC6\n\n"
  sudo apt install -y libc6:armhf

  printf "\n[-] Symbolic link libC6\n\n"
  sudo ln -s /lib/ld-linux-armhf.so.3 /lib/ld-linux.so.3

  printf "\n[-] Install ARMFH user space libraries\n\n"
# sudo apt install libbsd0:armhf libc6:armhf libdbus-1-3:armhf libdrm-amdgpu1:armhf libdrm-etnaviv1:armhf libdrm-freedreno1:armhf libdrm-nouveau2:armhf libdrm-radeon1:armhf libdrm2:armhf libedit2:armhf libelf1:armhf libexpat1:armhf  libfreetype6:armhf libgcc1:armhf libgcrypt20:armhf libgl1:armhf libgl1-mesa-dri:armhf libglapi-mesa:armhf libglvnd0:armhf libglx-mesa0:armhf libglx0:armhf libgomp1:armhf libgpg-error0:armhf libllvm7:armhf liblz4-1:armhf liblzma5:armhf libpng16-16:armhf libstdc++6:armhf libsystemd0:armhf libtinfo5:armhf libudev-dev:armhf libudev1:armhf libx11-6:armhf libx11-xcb1:armhf libxau6:armhf libxcb-dri2-0:armhf libxcb-dri3-0:armhf libxcb-glx0:armhf libxcb-present0:armhf libxcb-sync1:armhf libxcb1:armhf libxdamage1:armhf libxdmcp6:armhf libxext6:armhf libxfixes3:armhf libxshmfence1:armhf libxxf86vm1:armhf zlib1g:armhf libusb-1.0-0:armhf
sudo apt install -y libbsd0:armhf libc6:armhf libdbus-1-3:armhf libdrm-amdgpu1:armhf libdrm-etnaviv1:armhf libdrm-freedreno1:armhf libdrm-nouveau2:armhf libdrm-radeon1:armhf libdrm2:armhf libedit2:armhf libelf1:armhf libexpat1:armhf  libfreetype6:armhf libgcc1:armhf libgcrypt20:armhf libgl1:armhf libgl1-mesa-dri:armhf libglapi-mesa:armhf libglvnd0:armhf libglx-mesa0:armhf libglx0:armhf libgomp1:armhf libgpg-error0:armhf libllvm7:armhf liblz4-1:armhf liblzma5:armhf libpng16-16:armhf libsystemd0:armhf libtinfo5:armhf libudev-dev:armhf libudev1:armhf libx11-6:armhf libx11-xcb1:armhf libxau6:armhf libxcb-dri2-0:armhf libxcb-dri3-0:armhf libxcb-glx0:armhf libxcb-present0:armhf libxcb-sync1:armhf libxcb1:armhf libxdamage1:armhf libxdmcp6:armhf libxext6:armhf libxfixes3:armhf libxshmfence1:armhf libxxf86vm1:armhf zlib1g:armhf
}

remove.armhf() {
  printf "\n[-] Remove ARMFH user space libraries\n\n"
# sudo apt remove libbsd0:armhf libc6:armhf libdbus-1-3:armhf libdrm-amdgpu1:armhf libdrm-etnaviv1:armhf libdrm-freedreno1:armhf libdrm-nouveau2:armhf libdrm-radeon1:armhf libdrm2:armhf libedit2:armhf libelf1:armhf libexpat1:armhf  libfreetype6:armhf libgcc1:armhf libgcrypt20:armhf libgl1:armhf libgl1-mesa-dri:armhf libglapi-mesa:armhf libglvnd0:armhf libglx-mesa0:armhf libglx0:armhf libgomp1:armhf libgpg-error0:armhf libllvm7:armhf liblz4-1:armhf liblzma5:armhf libpng16-16:armhf libstdc++6:armhf libsystemd0:armhf libtinfo5:armhf libudev-dev:armhf libudev1:armhf libx11-6:armhf libx11-xcb1:armhf libxau6:armhf libxcb-dri2-0:armhf libxcb-dri3-0:armhf libxcb-glx0:armhf libxcb-present0:armhf libxcb-sync1:armhf libxcb1:armhf libxdamage1:armhf libxdmcp6:armhf libxext6:armhf libxfixes3:armhf libxshmfence1:armhf libxxf86vm1:armhf zlib1g:armhf libusb-1.0-0:armhf
sudo apt remove -y  --purge  libbsd0:armhf libc6:armhf libdbus-1-3:armhf libdrm-amdgpu1:armhf libdrm-etnaviv1:armhf libdrm-freedreno1:armhf libdrm-nouveau2:armhf libdrm-radeon1:armhf libdrm2:armhf libedit2:armhf libelf1:armhf libexpat1:armhf  libfreetype6:armhf libgcc1:armhf libgcrypt20:armhf libgl1:armhf libgl1-mesa-dri:armhf libglapi-mesa:armhf libglvnd0:armhf libglx-mesa0:armhf libglx0:armhf libgomp1:armhf libgpg-error0:armhf libllvm7:armhf liblz4-1:armhf liblzma5:armhf libpng16-16:armhf libsystemd0:armhf libtinfo5:armhf libudev-dev:armhf libudev1:armhf libx11-6:armhf libx11-xcb1:armhf libxau6:armhf libxcb-dri2-0:armhf libxcb-dri3-0:armhf libxcb-glx0:armhf libxcb-present0:armhf libxcb-sync1:armhf libxcb1:armhf libxdamage1:armhf libxdmcp6:armhf libxext6:armhf libxfixes3:armhf libxshmfence1:armhf libxxf86vm1:armhf zlib1g:armhf

  printf "\n[-] Remove Symbolic link libC6\n\n"
  sudo rm /lib/ld-linux.so.3

  printf "\n[-] Remove libC6\n\n"
  sudo apt remove --purge -y libc6:armhf

  printf "\n[-] Remove ARMHF\n\n"
  sudo dpkg --remove-architecture armhf
  sudo apt update
}

if [[ ${ACTION} == "install" ]]; then
  install.armhf
elif [[ ${ACTION} == "remove" ]]; then
  remove.armhf
else
  printf "\n[-] Uknown command: ${ACTION}... exiting\n\n"
  exit 2
fi

printf "\n[-] COMPLETE\n\n"
