#!/usr/bin/env bash
# could use this to get the IP address
# ifconfig eth0 | grep inet | grep -v inet6 | awk '{print $2}'
# need to specify the network interface to use, e.g: eth0

if [ $# -eq 0 ] || [ $# -lt 1 ]
  then
    echo ""
    echo " *******************************"
    echo " Install Indigo Server"
    echo " *******************************"
		echo ": "
		echo ": Requires at least one driver"
    echo ": e.g."
    echo ": install_indigo indigo_ccd_asi"
    echo ": or..."
    echo ": install_indigo indigo_aux_upb indigo_ccd_asi indigo_aux_arteskyflat indigo_gps_gpsd -i indi_paramount_telescope"
    echo ""
		exit 1
fi

SRVC_NAME=indigo-srv
SRVC=${SRVC_NAME}.service
SRVC_DIR=${HOME}'/.config/systemd/user'
SRVC_FILE=${SRVC_DIR}/${SRVC}
SOURCES_DIR='/etc/apt/sources.list.d'
SOURCES_FILE=${SOURCES_DIR}/${SRVC_NAME}.list
SRVC_AUTOSTART=${HOME}'/.config/autostart/'${SRVC_NAME}.desktop
AUTOSTART_DIR=${HOME}'/.config/autostart'

drivers=()
while [[ $# -gt 0 ]]; do
  param="$1"
  if [[ ${param} == "install-indigo" ]]
  then
    shift
  else
    drivers+="$param "  # save it in an array for later
    shift # move to next
  fi
done

echo ""
echo " *******************************"
echo " Drivers found: "${drivers}
echo " *******************************"
echo ""

install_dir=$(pwd)

install.autostart.file() {
  mkdir -p ${AUTOSTART_DIR}
  echo ""
	echo " *******************************"
  echo " Install autostart: "${SRVC_AUTOSTART}
  echo " *******************************"
	echo '' > ${SRVC_AUTOSTART}
  echo '[Desktop Entry]' >> ${SRVC_AUTOSTART}
	echo 'Type=Application' >> ${SRVC_AUTOSTART}
	echo 'Name='${SRVC_NAME} >> ${SRVC_AUTOSTART}
	echo 'Exec=systemctl --user start '${SRVC} >> ${SRVC_AUTOSTART}
	echo 'X-MATE-Autostart-enabled=true' >> ${SRVC_AUTOSTART}
	echo 'X-GNOME-Autostart-enabled=true' >> ${SRVC_AUTOSTART}
}

install.service.file() {
  mkdir -p ${SRVC_DIR}
  echo ""
  echo " *******************************"
  echo " Install service: "${SRVC_FILE}
  echo " *******************************"
  echo '' > ${SRVC_FILE}
  echo '[Unit]' >> ${SRVC_FILE}
  echo 'Description=INDIGO Server' >> ${SRVC_FILE}
  echo 'After=multi-user.target syslog.target network.target remote-fs.target' >> ${SRVC_FILE}
  echo '' >> ${SRVC_FILE}
  echo '[Service]' >> ${SRVC_FILE}
  echo 'Type=idle' >> ${SRVC_FILE}
  echo 'PIDFile=/var/run/'${SRVC_NAME}'.pid' >> ${SRVC_FILE}
  # echo 'WorkingDirectory='${install_dir}'/bin' >> ${SRVC_FILE}
  echo '' >> ${SRVC_FILE}
  echo 'ExecStartPre=/bin/rm -f /var/run/'${SRVC_NAME}'.pid' >> ${SRVC_FILE}
  echo 'ExecStart=/usr/bin/indigo_server '${drivers} >> ${SRVC_FILE}
  echo '' >> ${SRVC_FILE}
  echo 'Restart=always' >> ${SRVC_FILE}
  echo 'RestartSec=10' >> ${SRVC_FILE}
  echo '' >> ${SRVC_FILE}
  echo 'ExecStop=/bin/kill -s QUIT $MAINPID' >> ${SRVC_FILE}
  echo 'KillSignal=SIGKILL' >> ${SRVC_FILE}
  echo '' >> ${SRVC_FILE}
  echo '[Install]' >> ${SRVC_FILE}
  echo "WantedBy=multi-user.target" >> ${SRVC_FILE}
}

install.sources.file() {
  echo ""
  echo " *******************************"
  echo " Install Sources: "${SOURCES_FILE}
  echo " *******************************"
sudo bash -c "cat > ${SOURCES_FILE} <<- EOF
deb [trusted=yes] https://indigo-astronomy.github.io/indigo_ppa/ppa indigo main
EOF"
}

printf "\n[-] Create User Service File and start\n\n"
install.sources.file
install.service.file
install.autostart.file

printf "\n[-] Install Service: ${SRVC}\n\n"
sudo apt update
sudo apt-get install indigo
sudo systemctl daemon-reload
sudo systemctl stop indigo-environment
sudo systemctl disable indigo-environment

printf "\n[-] Start service\n\n"
systemctl --user daemon-reload
systemctl --user enable ${SRVC}
systemctl --user start ${SRVC}
