#!/usr/bin/env bash
# could use this to get the IP address
# ifconfig eth0 | grep inet | grep -v inet6 | awk '{print $2}'
# need to specify the network interface to use, e.g: eth0

SRVC_NAME=xfce4-clipman
SRVC_DIR=/usr/bin
SRVC_AUTOSTART=${HOME}'/.config/autostart/'${SRVC_NAME}.desktop
AUTOSTART_DIR=${HOME}'/.config/autostart'

install_dir=$(pwd)

install.autostart.file() {
  printf "\n[-] Install User ${SRVC_AUTOSTART}\n\n"
  mkdir -p ${AUTOSTART_DIR}
  bash -c "cat << EOF > ${SRVC_AUTOSTART}
[Desktop Entry]
Type=Application
Exec=${SRVC_DIR}/${SRVC_NAME}
Hidden=false
X-MATE-Autostart-enabled=true
Name[C]=Clipman
Name=Clipman
Comment[C]=
Comment=
EOF
"
}

install.app() {
  printf "\n[-] Install ${SRVC_NAME}\n\n"
  sudo apt update
  sudo apt install -y ${SRVC_NAME} ${SRVC_NAME}-plugin
}

install.app
install.autostart.file

printf "\n[-] COMPLETED ${SRVC_NAME}\n\n"
