#!/usr/bin/env bash
# could use this to get the IP address
# ifconfig eth0 | grep inet | grep -v inet6 | awk '{print $2}'
# need to specify the network interface to use, e.g: eth0

SRVC_NAME=noVNC
SRVC=${SRVC_NAME}.service
SRVC_DIR=${HOME}'/.config/systemd/user'
SRC_DIR=${HOME}'/src'
APP_DIR=${SRC_DIR}'/noVNC'
SRVC_FILE=${SRVC_DIR}/${SRVC}
SOURCES_DIR='/etc/apt/sources.list.d'
SOURCES_FILE=${SOURCES_DIR}/${SRVC_NAME}.list
SRVC_AUTOSTART=${HOME}'/.config/autostart/'${SRVC_NAME}.desktop
AUTOSTART_DIR=${HOME}'/.config/autostart'

install_dir=$(pwd)

install.autostart.file() {
  printf "\n[-] Install autostart: ${SRVC_AUTOSTART}\n\n"
  mkdir -p ${AUTOSTART_DIR}
  dd of=${SRVC_AUTOSTART} << EOF
[Desktop Entry]
Type=Application
Name=${SRVC_NAME}
Exec=systemctl --user start ${SRVC}
X-MATE-Autostart-enabled=true
X-GNOME-Autostart-enabled=true
EOF
}

install.service.file() {
  mkdir -p ${SRVC_DIR}
  printf "\n[-] Install ${SRVC_NAME} service file: ${SRVC_FILE}\n\n"
  sudo dd of=${SRVC_FILE} << EOF
[Unit]
Description=${SRVC_NAME} Server
After=multi-user.target syslog.target network.target remote-fs.target

[Service]
Type=idle
PIDFile=/var/run/${SRVC_NAME}.pid
# WorkingDirectory=${install_dir}/bin

ExecStartPre=/bin/rm -f /var/run/${SRVC_NAME}.pid
ExecStart='${APP_DIR}'/utils/novnc_proxy --vnc localhost:5900

Restart=always
RestartSec=10'

ExecStop=/bin/kill -s QUIT $MAINPID
KillSignal=SIGKILL

[Install]
WantedBy=multi-user.target
EOF
  sudo systemctl --user daemon-reload
}

install.sources.file() {
  printf "\n[-] Install ${SRVC_NAME}\n\n"
  mkdir -p ${SRC_DIR}
  cd ${SRC_DIR}
  git clone https://github.com/novnc/noVNC.git
}

install.dependencies() {
  printf "\n[-] Install ${SRVC_NAME} dependencies\n\n"
  sudo apt update
  sudo apt install git
}

install.dependencies

install.sources.file

install.service.file
#install.autostart.file

printf "\n[-] Start service\n\n"
systemctl --user enable ${SRVC}
systemctl --user start ${SRVC}

printf "\n[-] Browser: e.g.: http://localhost:6080/vnc.html?host=localhost&port=6080\n\n"
